nats:
  url: nats://127.0.0.1:4222
  username: midimix
  passwordFile: /run/secrets/nats/password

midi:
  input: MIDI Mix MIDI 1
  output: MIDI Mix MIDI 1
  channel: 0
  maxInputValue: 127

pulseaudio:
  targets:
    - type: PlaybackStream
      name: spotify
      mute: 1
      presence: 3
      volume: 19

    - type: PlaybackStream
      name: Firefox
      mute: 4
      presence: 6
      volume: 23

    - type: PlaybackStream
      name: Chromium
      mute: 7
      presence: 9
      volume: 27

    - type: Sink
      name: Focusrite Scarlett 2i2 2nd Gen Analog Stereo
      mute: 10
      presence: 12
      volume: 31

    - type: Source
      name: Webcam C270 Mono
      mute: 13
      presence: 15
      volume: 49

    - type: Source
      name: Jabra Link 380 Mono
      mute: 16
      presence: 18
      volume: 53

actions:
  - type: LedColor
    config:
      host: sitting-desk
      controls: [16, 17, 18]
      format: hsv

  - type: LedColor
    config:
      host: standing-desk
      controls: [20, 21, 22]
      format: hsv

  - type: LedColor
    config:
      host: deskled
      controls: [24, 25, 26]
      format: hsv

  - type: LedColor
    config:
      host: ceiling-led
      controls: [28, 29, 30]
      format: hsv

  - type: LedColor
    config:
      host: ledtable
      controls: [46, 47, 48]
      format: hsv
